/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cosa;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import kfjlgdfkd.MyTableModel;

/**
 *
 * @author Alumno CG
 */
public class GUI extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GUI
     */
    
    MyTableModel tableModel = new MyTableModel();
    
    public GUI() {
        initComponents();
        init();
    }
    
    private void init (){
        setLocationRelativeTo(null);
        menu_añadir.addActionListener(this);
        menu_salir.addActionListener(this);
        table_cuentas.setModel(tableModel);
        menu_agregar.addActionListener(this);
        menu_eliminar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menu_agregar = new javax.swing.JMenuItem();
        menu_eliminar = new javax.swing.JMenuItem();
        myPanel1 = new cosa.MyPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cuentas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_añadir = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();

        menu_agregar.setText("Agregar");
        jPopupMenu1.add(menu_agregar);

        menu_eliminar.setText("Eliminar");
        jPopupMenu1.add(menu_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_cuentas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(table_cuentas);

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        menu_añadir.setText("Añadir Cuenta");
        jMenu1.add(menu_añadir);

        menu_salir.setText("Salir");
        jMenu1.add(menu_salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_agregar;
    private javax.swing.JMenuItem menu_añadir;
    private javax.swing.JMenuItem menu_eliminar;
    private javax.swing.JMenuItem menu_salir;
    private cosa.MyPanel myPanel1;
    private javax.swing.JTable table_cuentas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        Object origin = e.getSource();
        if (origin == menu_añadir){
            añadir();
        } else if (origin == menu_salir){
            System.exit(0);
        } else if (origin == menu_agregar){
            añadir();
        } else if (origin == menu_eliminar){
            eliminar();
        }
    }
    
    private void eliminar(){
        int row = table_cuentas.getSelectedRow();
        if (row!=-1){
            tableModel.removeRow(row);
        }
    }
    
    private void añadir(){
        AñadirCuenta dialog = new AñadirCuenta(this, rootPaneCheckingEnabled);
        int respuesta = dialog.showDialog();
        if (respuesta == AñadirCuenta.ACEPTAR) {
            if (dialog.isNormal()) {
                tableModel.addRow(dialog.getCuentaNormal());
            } else {
                tableModel.addRow(dialog.getCuentaPremium());
            }
     
        } else {
            System.out.println("cancelaste");
        }
    }
}
